name: Create TODO Issues

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  todo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run TODO to Issue
        uses: alstr/todo-to-issue-action@v2.6.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
